# Generated by Django 2.2 on 2022-02-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_staff',
            new_name='is_staff',
        ),
    ]
